server:
  #??
  port: 8080
spring:
  application:
    #????
    name: my-restaurant
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_restaurant?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    #mysql??
    username: root
    #mysql??
    password: 123456
#mybatisplus??
mybatis-plus:
  #mybatis?????????
  type-aliases-package: cn.gdsdxy.myrestaurant.entity
  #mybatisplus?mapper xml????
  mapper-locations: classpath:mapper/*.xml
  global-config:
    map-underscore-to-camel-case: true
    db-config:
      #??????
      logic-delete-field: isDeleted
      #??????
      logic-delete-value: 1 # ??????(??? 1)
      #???????
      logic-not-delete-value: 0 # ??????(??? 0)
      #NOT_EMPTY ???????NULL???????
      insert-strategy: not_empty
      update-strategy: not_empty